version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: smartroads-ai-face-detection-backend-alpha1
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: smartroads-ai-face-detection-frontend-alpha1
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - SERVER_URL=http://backend:8000/detect_face
    restart: unless-stopped